### PR TITLE
Fix for issue #73: Allow ScopeManager.active().close() and let it be a no-op

### PR DESCRIPTION
**Pull request by hanson76**

### CODE REVIEW

**Comment by adriancole** [comment]
Why would someone close like this? Is there a project you can reference or
a spec?

I think the api is a mistake. It shouldnt return Scope at all, rather only
the current span.

**Comment by hanson76** [comment]
One example is opentracing-contrib java-spring-web [1]

There are also cases where you want to do 
try (Scope scope = opentracing.scopeManager().active())  {
 // Do something
}

Some implementations of the tracing API might need to do things on scope close.

[1] https://github.com/opentracing-contrib/java-spring-web/blob/master/opentracing-spring-web/src/main/java/io/opentracing/contrib/spring/web/interceptor/TracingHandlerInterceptor.java

**Comment by adriancole** [comment]
Thanks for the background. FYI in spring we stopped using MVC filters for lifecycle, rather deferring to servlet layer. MVC filters are a bit unreliable and also can be cut-off by servlet layer filters. This change is available in Brave 4.18+ https://github.com/openzipkin/brave/releases/tag/4.18.2

**Comment by adriancole** [comment]
going out now in 0.30.1

**Pull request merged**
